### ISSUE TITLE
Shouldn't this be an array? Don't you want multiple cohorts per subject

### ISSUE THREAD

**Issue by arthurbernierjr** [sanlaelaecho/gradebook-API#1]
https://github.com/sanlaelaecho/gradebook-API/blob/6bdf872512bd1b932123100df707939a252b9748/models/subject.js#L2-L11

```js
    cohorts: [{type: Schema.Types.ObjectId, ref: 'Cohort'}]
```

Thought process is There is one `Subject` example `Coding` and there are multiple cohorts `Donna, Frances, Evelyn, Madeline, Erica` etc

**Comment by sanlaelaecho** [comment]
Understood! Will update
